### ISSUE TITLE
Please add License 

### ISSUE THREAD

**Issue by mavemuri** [TykTechnologies/drl#17]
looks like this gets pulled in via indirect dependencies of other tyk/projects but its unclear what license this particular project has

**Comment by buger** [comment]
Done, it is fully Tyk code, and just applied MPL 2 license to it, the same as gateway has.

**Comment by mavemuri** [comment]
thanks @buger ! Greatly appreciate the quick response 
Just want to confirm- may we assume that this is retroactive? i.e, it has always been under MPL2/older versions are/were under MPL2 as well?

**Comment by buger** [comment]
Yes, correct.
